.eslintrc.js, CHANGELOG.md, aspida.config.js, package.json, samples/externals.json, samples/externals/$api.ts, samples/externals/@types.ts, samples/externals/users/_user_id@string/orders/_order_id@string.ts, samples/externals/users/_user_id@string/orders/index.ts, samples/externals/users/_user_id@string/orders/purchase/invoice.ts, samples/externals/users/_user_id@string/orders/purchase/wallet.ts, samples/externals/users/_user_id@string/orders/unsubscribe.ts, samples/externals/users/_user_id@string/orders/update/renew.ts, samples/externals/users/_user_id@string/phone-numbers/_phone_number@string/orders/index.ts, samples/externals/users/_user_id@string/phone-numbers/_phone_number@string/orders/purchase/invoice.ts, samples/externals/users/_user_id@string/phone-numbers/_phone_number@string/orders/purchase/wallet.ts, src/buildTemplate.ts, src/buildV3.ts, src/builderUtils/converters.ts, src/builderUtils/resolvers.ts, src/getConfig.ts, src/resolveExternalRefs.ts
=> chore(release): 0.7.0

.github/workflows/nodejs.yml, CHANGELOG.md, package.json, src/resolveExternalRefs.ts, yarn.lock
=> chore(release): 0.7.1

CHANGELOG.md, package.json, samples/externals/$api.ts, samples/freee/$api.ts, samples/openapi/$api.ts, samples/simple/$api.ts, samples/strapi/$api.ts, samples/swagger/$api.ts, src/resolveExternalRefs.ts, yarn.lock
=> chore(release): 0.8.0

CHANGELOG.md, README.md, package.json, src/getConfig.ts, yarn.lock
=> chore(release): 0.10.1

CHANGELOG.md, package.json, src/buildV3.ts, yarn.lock
=> chore(release): 0.15.1

aspida.config.js, samples/nullable-object.yml, samples/nullable-object/$api.ts, samples/nullable-object/@types.ts, samples/nullable-object/user/$api.ts, samples/nullable-object/user/index.ts, src/buildV3.ts
=> `import * as Types ...`の記述条件の追加とサンプルの追加

CHANGELOG.md, aspida.config.js, package.json, samples/nullable-object.yml, samples/nullable-object/$api.ts, samples/nullable-object/@types.ts, samples/nullable-object/user/$api.ts, samples/nullable-object/user/index.ts, src/buildV3.ts, src/resolveExternalRefs.ts, yarn.lock
=> chore(release): 0.15.2

CHANGELOG.md, package.json, yarn.lock
=> chore(release): 0.15.3

CHANGELOG.md, package.json, samples/freee/$api.ts, samples/freee/api/$api.ts, samples/freee/api/1/$api.ts, samples/freee/api/1/journals/$api.ts, samples/freee/api/1/journals/reports/$api.ts, samples/freee/api/1/journals/reports/_id@number/download/index.ts, src/buildV3.ts, src/builderUtils/converters.ts, yarn.lock
=> chore(release): 0.16.2

aspida.config.js, samples/array-one-of.yml, samples/array-one-of/$api.ts, samples/array-one-of/@types/index.ts, samples/array-one-of/user/$api.ts, samples/array-one-of/user/index.ts, src/buildV3.ts
Fix
`
export type User = {
id: string
roles: (Types.RoleA | RoleB)[]
}
`
↓
`
export type User = {
id: string
roles: (RoleA | RoleB)[]
}
`
=> fix: array one of

.eslintignore, .github/workflows/nodejs.yml, .gitignore, .prettierignore, .vscode/extensions.json, .vscode/settings.json, CHANGELOG.md, aspida.config.js, jest.config.ts, package.json, samples/array-one-of.yml, samples/array-one-of/$api.ts, samples/array-one-of/@types/index.ts, samples/array-one-of/user/$api.ts, samples/array-one-of/user/index.ts, src/buildV3.ts, yarn.lock
=> chore(release): 0.16.5

__tests__/outputFilePath.spec.ts, package.json, src/buildV3.ts, src/cli.ts, src/getConfig.ts, src/index.ts, src/outputFilePath.ts, src/resolveExternalRefs.ts, src/writeRouteFile.ts, yarn.lock
https://zenn.dev/seya/articles/bf52abf0b2f5a7 のように -o のプレフィクスで出力するフォルダーを変更できるようにした
例:
```
npx openapi2aspida -i=hoge/openapi.yml -o=api/hoge/fuga
```
と設定すると`api/hoge/fuga` の下にaspidaのコードが生成されるようにしました。
=> -o で書き出すフォルダーを変更できるようにした

README.md
`Readme.md` にhttps://github.com/aspida/openapi2aspida/pull/155 で追加したoutput Optionについての説明を追加しました。
=> docs:  Readme.md にoutput Optionについての説明を追加

src/builderUtils/props2String.ts
=> [fix] fix #159

CHANGELOG.md, README.md, __tests__/outputFilePath.spec.ts, package-lock.json, package.json, samples/swagger.yaml, samples/swagger/$api.ts, samples/swagger/hello/$api.ts, samples/swagger/hello/index.ts, src/buildV3.ts, src/builderUtils/props2String.ts, src/cli.ts, src/getConfig.ts, src/index.ts, src/outputFilePath.ts, src/resolveExternalRefs.ts, src/writeRouteFile.ts, yarn.lock
=> chore(release): 0.17.0

src/buildV3.ts
=> Copy of 137

src/buildV3.ts
Issue Number: #136
This PR will fix #136.
I think we should add some test codes, but I didn't know the rules for test cases. Please let me know if there is a proper way.
=> Support redirect status code

aspida.config.js, src/buildTemplate.ts, src/buildV3.ts, src/builderUtils/getDirName.ts, src/getConfig.ts
- resolves #
- resolves #
- ...
=> revert: replaceLeadingAtMark of PR #146

aspida.config.js, package.json, samples/request-bodies.yml, samples/request-bodies/$api.ts, samples/request-bodies/@types/index.ts, samples/request-bodies/users/$api.ts, samples/request-bodies/users/index.ts, samples/swagger/@types/index.ts, src/buildTemplate.ts, src/buildV3.ts, src/builderUtils/requestBodies2Props.ts, yarn.lock
- resolves #
- resolves #160
- add support requestBodies components
- add sample yaml and generated codes
- wip: unexpected diff
- add prepare script
- add files
- mkdir before build
- Fix unexpected types for samples/swagger
@MH4GF さんのコミットをベースに修正を加えました。
=> feat: add support RequestBodies components

README.md
Hi, there. This PR has only tiny change. I found some implicit CLI options, and added them to `README.md`.
- ~~resolves #~~
- ~~resolves #~~
- fix typo of CLI options (`--outputdir`)
- add undocumented CLI options
N/A
=> [docs] add description for CLI optiions

CHANGELOG.md, package.json, yarn.lock
- resolves #
- resolves #
- ...
=> chore: add minimist to devDependencies

CHANGELOG.md, package.json
- resolves #
- resolves #
- ...
=> chore: release v0.21.0
